### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by JuhQ** [Vanamo/reseptisovellus#1]
Huomioita

Sivuston käytettävyys
  - reseptin hakuinputin focus näyttää muuttavan listan järjestystä, mutta siirtää vain parin reseptin paikkaa, outoa
  - olisi kiva jos listalla olevaa sydäntä voisi klikata
  - sivusto toimii tosi hyvin

Backend
  - ensimmäisen commitin myötä node_modules hakemisto päätynyt gitiin
    - tässä tosi hyvä githubin tarjoama repository joka tarjoaa `.gitignore` tiedostoja eri kielille
      - https://github.com/github/gitignore
      - node löytyy sieltä myös https://github.com/github/gitignore/blob/master/Node.gitignore
  - olisi kiva nähdä middlewareja routeissa
  - koodissa käytetty hyviä käytänteitä, ei mitään suurta huomautettavaa

Frontend
  - App.js importit olisi hyvä sortata niin että alkuun on npm komponentit ja sen jälkeen omat komponentit
  - tätä voisi yksinkertaistamaan palauttamaan suoraan funktion arvon sen sijaan että se ensin laitetaan muuttujaan ja palautetaan vasta sitten
    ```
    const recipeById = (id) => {
      const recipe = this.props.recipes.find(r => r.id === String(id))
      return recipe
    }
    ```
    muotoon
    ```
    const recipeById = (id) => {
      return this.props.recipes.find(r => r.id === String(id))
    }
    ```
    tai
    ```
    const recipeById = (id) =>
      this.props.recipes.find(r => r.id === String(id))
    ```
  - olisi hyvä että funktiokutsun aloitus ja lopetus olisi samoilla riveillä
    ```
    const MenuComponent = withRouter(props =>
      <NavigationMenu {...props}
        user={this.props.user}
        handleLogout={this.handleLogout}
      />)
    ```
    muotoon
    ```
    const MenuComponent = withRouter(props =>
      <NavigationMenu {...props}
        user={this.props.user}
        handleLogout={this.handleLogout}
      />
    )
    ```
      - muutos on tosi pieni mutta helpottaa lukemista kun näkee heti missä funktion kutsuminen loppuu ja mikä on looginen koodiblock
  - reduxia ja reducereita käytetty tosi hyvin
  - mitä tässä tilanteessa käy jos käyttäjä painaa confirm laatikon cancel nappia?
    ```
    let tag = null
    if (window.confirm(`Haluatko varmasti lisätä uuden tagin '${value}'?`)) {
      tag = await this.props.newTag(newTag)
    }

    const tags = this.state.tags.concat(tag.id)
    ```

  - suosittelen rivittämään koodia jotta luettavuus paranee, aina kannattaa suosia hyvää luettavuutta
    ```
    return options.map(option => ({ key: option.id, text: option.name, value: option.id }))
    ```
    muotoon
    ```
    return options.map(option => ({
      key: option.id,
      text: option.name,
      value: option.id
    }))
    ```
      - siinä on vähän enemmän rivejä mutta arvot on helpompi bongata

Rock on!
Kaiken kaikkiaan tosi hyvää työtä!

**Comment by Vanamo** [comment]
Kiitos palautteesta! Nyt vasta huomasin tämän. Kiva saada palautetta :)
